paypal/react-paypal-js

- README.md
The goal with PR is to better explain the problems that react-paypal-js is solving. Here's a screenshot this new section in the readme:
> Explain why the world needs react-paypal-js

- .github/workflows/main.yml
- .github/workflows/storybook.yml
This PR adds a Github `storybook.yml` to deploy storybook on pushes/merges to main. It utilizes the [path workflow](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) which allows us to check for any changes to `src/` or the README (synced with our Getting Started page). This way we only deploy on main when there are changes available.
This PR also adds an update to`main.yml` to check storybook builds on every pull request.
Why _not_ automate storybook deploys?
> Add Github Action to deploy Storybook

- README.md
The GitHub Actions badge doesn't have a flat style. This PR removes the flat style from the other badges so everything matches. Here's a screenshot of the new look:
> Remove flat style from badges

- scripts/publish.js
Updates the`publish.js` script to use a callback to pass in the OTP flag with `npm publish`.
This PR also removes the `npm run deploy-storybook` command. This is being replaced by a Github Action in an upcoming PR.
Attempting to run `npm publish` with the `exec` command from `shelljs` exits before allowing the user to enter an OTP. 2FA is required to publish to public npm, therefore the script did not work.
> Update publish script

- __mocks__/@paypal/paypal-js.js
- src/ScriptContext.js
- src/ScriptContext.test.js
- src/stories/Subscriptions.stories.js
- src/stories/usePayPalScriptReducer.stories.js
This PR adds a generic `resetOptions` action for changing the sdk params with the dispatcher. The dispatcher is used for the reload use case. For example, the following use cases would use `resetOptions`:
- Updating currency
- Toggling the transaction type from Order to Subscription
Originally I added the `updateCurrency` action thinking each use case could have it's own specific action. Looking back, I think that was a mistake because there are so many different combinations of params that could be sent to the sdk, and we can't add a specific action for every use case. Instead, let's have one function that's able to set params and pass them through to paypal-js to reload the sdk. We can remove `updateCurrency` when we do a major version bump.
> Add 'resetOptions' action for dispatcher for reloading use case

- src/components/PayPalButtons.js
- src/components/PayPalButtons.test.js
- src/components/PayPalMarks.js
- src/components/PayPalMarks.test.js
- src/components/PayPalMessages.js
- src/stories/PayPalButtons.stories.js
- src/stories/usePayPalScriptReducer.stories.js
This PR fixes #45 by catching and logging any errors returned when rendering components. 
Under the hood, the PayPal JS SDK uses zoid and `render()` is actually an async function that returns a promise: https://github.com/krakenjs/zoid/issues/218#issuecomment-463884767. This PR catches render errors and logs them using `console.error()`.
> Catch and log errors from zoid render()

- src/stories/PayPalButtons.stories.js
- src/stories/PayPalMarks.stories.js
- src/stories/Subscriptions.stories.js
This PR fixes #50 and makes sure the default inline guest feature works with the Standard Cards button for the [Buttons Storybook Demo](https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalbuttons--default). Ex:
This bug was only for the storybook demos. It turns out the storybook docs addon passes default values for props for component stories like the Buttons story even though we are not passing default prop type values. Passing default functions to most callbacks doesn't matter. But with the `onShippingChange` callback it does matter and using that option forces the user into the popup experience with the Standard Cards button. This PR passes null instead of a noop function to `onShippingChange` so the inline guest functionality works as expected.
> Opt-out from using onShippingChange() callback with storybook demo

- README.md
- src/components/PayPalButtons.js
- src/components/PayPalButtons.test.js
- src/stories/PayPalButtons.stories.js
I recently learned that `shippingPreference` is not a valid option for Buttons. This PR removes it.
> Remove shipping preferences prop

- .github/workflows/close-stale-issues.yml
This PR adds a new GitHub Action called [Close Stale Issues](https://github.com/marketplace/actions/close-stale-issues)
It's currently configured to label an issue or PR as stale after 45 days of no activity. And then close it out 5 days later if there's still no activity. I used the same polite messaging that React does for their automated issue management (https://github.com/facebook/react/blob/master/.github/stale.yml).
The plan is to test this out in react-paypal-js first. If it goes well then we can add it to more repos.
> Add github action for managing stale issues

- src/stories/PayPalButtons.stories.js
This PR adds a new story for rendering a standalone button as small as possible. It also simplifies the storybook implementation for Buttons.
I also updated the "Stand alone" button story to use PayPal instead of PayLater since the PayLater button may not show to some users based on their country.
> Add a tiny button example

- babel.config.js
- package-lock.json
- package.json
- rollup.config.js
- src/ScriptContext.tsx
- src/components/PayPalButtons.test.js
- src/components/PayPalButtons.tsx
- src/components/PayPalMarks.test.js
- src/components/PayPalMarks.tsx
- src/components/PayPalMessages.tsx
- src/index.ts
- src/types.d.ts
- tsconfig.json
Happy new year everyone! I come bearing the gift of types 🎁 
Use the latest beta to test out the types:
```
npm install @paypal/react-paypal-js@beta
```
There are a lot of `@ts-expect-error` statements being used to avoid compile time errors. These are code smells and should be cleaned up before merging this PR. I could use some help with this. I would gladly accept PRs to this "typescript" branch.
I decided to keep the Proptypes with the idea that they are for runtime validation and the TypeScript types are for compile time validation. For more info see: https://stackoverflow.com/a/54690878
Related issues: #69 #53
> Use TypeScript

- src/components/PayPalButtons.test.js
- src/components/PayPalButtons.tsx
- src/components/__snapshots__/PayPalButtons.test.js.snap
This PR attempts to limit rendering errors related to the Buttons container being removed before async rendering completes. It's inspired by this PR for the zoid react driver that ships with the JS SDK: https://github.com/krakenjs/zoid/pull/335.
Related: #85
> Do not throw button render errors when ref is invalid

- src/components/PayPalButtons.test.js
- src/components/PayPalButtons.tsx
- src/stories/VenmoButton.stories.js
This PR updates the Buttons component to render null by default when ineligible. It also supports rendering custom content when ineligible using `props.children`.
Resolves #90.
> feat: support rendering custom content when ineligible

- README.md
- src/ScriptContext.test.js
- src/ScriptContext.tsx
- src/stories/PayPalScriptProvider.stories.js
- src/stories/usePayPalScriptReducer.stories.js
This PR adds a new `deferLoading` prop to the `<PayPalScriptProvider>` for controlling when the sdk script loads. Resolves #89. 
`deferLoading` prop behavior:
- set to false by default since we usually know all the sdk script params up front and want to load asap in order for the Buttons to render as fast as possible for buyers. 
- can be set to true to prevent loading the JS SDK script when the provider renders. Use `deferLoading={true}` initially and then dispatch an action later on in the app's life cycle to load the sdk script.
One thing to note is the `<PayPalScriptProvider>` props are currently designed to only support initial load. This new "deferLoading" prop supports prop changes. If you initially set it to true and then change it to false when rerendering, it will trigger a …
> feat: add deferLoading option to control when sdk script loads

- src/components/PayPalButtons.test.js
- src/components/PayPalButtons.tsx
- src/components/PayPalMessages.tsx
- src/stories/PayPalButtons.stories.js
Fixes https://github.com/paypal/react-paypal-js/issues/98
This makes the `forceReRender` an array, so we can add multiple things to the `useEffect` inside the component.
This enables us to add things like `currency`, `amount`, `order` and etc to the `forceReRender`, so it is always correct at the moment that the user clicks the button to Checkout.
This is a breaking change.
> Changing forceReRender to an array

- src/ScriptContext.tsx
- Created `ScriptLoadingState` type from the union of the enum `SCRIPT_LOADING_STATE` and used it 
as a possible values for `setLoadingStatus` to avoid type error when passing a valid string value on the dispatch function.
> fix: typescript type for `ScriptReducerAction`

- src/stories/PayPalButtons.stories.js
- src/stories/PayPalMarks.stories.js
- src/stories/PayPalMessages.stories.js
- src/stories/Subscriptions.stories.js
- src/stories/VenmoButton.stories.js
- src/stories/utils.js
This PR updates the storybook demo site to pass query string params through to the JS SDK. 
For example, when running locally and you can pass a custom `client-id` and `components` list in the query string and the JS SDK will apply that:
http://localhost:6006/?path=/story/example-paypalbuttons--default&client-id=sb&components=buttons,messages,hosted-fields
> feat(storybook): add support for overriding js sdk query params

- src/index.ts
We prevent typescript from generating declarations that reference the `@paypal/sdk-constants` package. This package does not provide types, instead we use our own type declarations in `./src/types.d.ts`. These declarations are not available to users of the library.
Fixes https://github.com/paypal/react-paypal-js/issues/125
> fix: type declarations don’t depend on internal typings

- package.json
- tsconfig.declarations.json
I noticed that types for the storybook stories were being included in the generated declarations. This PR adds a new typescript config to exclude them.
cc: @geigerzaehler
> fix(release): do not publish types from storybook

- src/stories/PayPalButtons.stories.tsx
We recently added support for Donations to the JS SDK with the v2 orders api. This PR adds an example Donation button to storybook.
Resolves: #124
> chore(storybook): add donation example

- src/components/PayPalMarks.test.js
- src/components/PayPalMarks.tsx
- src/context/scriptProviderContext.ts
The PayPalMarks component doesn't re-render on fundingSource props changes. The component has the fundingSource as a dependency in the useEffect but was disabled because an if statement inside the useEffect hook.
With this PR we fix that problem and allows re-render the PayPalMarks component when any useEffect dependency changes.
> PayPalMarks allows re-render on fundingSource changes

- src/components/PayPalMarks.test.js
- src/components/PayPalMarks.tsx
With this PR we enable children in the PayPalMarks component. To allows the creation of custom components when the marks   is ineligible ins the same way we support in PayPalButtons.
Now we can use this code below: 
```jsx
<PayPalMarks className="mark-container">
<div className="ineligible"></div>
</PayPalMarks>
```
When Marks is ineligible will render the children component.
> Support PayPalMarks children

- src/components/PayPalButtons.test.js
- src/components/PayPalButtons.tsx
- src/components/PayPalMarks.tsx
- src/components/braintree/BraintreePayPalButtons.tsx
- src/types/paypalButtonTypes.ts
- src/types/scriptProviderTypes.ts
In this PR we unified the children signature type on all the component [PayPalButtons, PayPalBraintreeButtons, PayPalMarks].
> Same signature on all the children components

- package-lock.json
- package.json
- src/stories/PayPalMessages.stories.tsx
- src/stories/braintree/BraintreePayPalButtons.stories.tsx
- src/stories/payPalButtons/PayPalButtons.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFieldsProvider.stories.tsx
- src/stories/payPalMarks/PayPalMarks.stories.tsx
- src/stories/payPalScriptProvider/PayPalScriptProvider.stories.tsx
- src/stories/subscriptions/Subscriptions.stories.tsx
- src/stories/venmo/VenmoButton.stories.tsx
The PR contains the latest version for all the outdated dependencies. Except for React, now I think we'll keep version 16.
To keep sync the repo with the latest versions of the used dependencies to avoid any kind of bugs/vulnerabilities.
> Upgrade dependencies

- package-lock.json
- package.json
- src/components/PayPalButtons.test.tsx
- src/components/PayPalButtons.tsx
- src/components/PayPalMarks.tsx
- src/components/PayPalMessages.tsx
- src/components/PayPalScriptProvider.test.tsx
- src/components/braintree/BraintreePayPalButtons.test.tsx
- src/components/hostedFields/PayPalHostedFieldsProvider.tsx
- src/context/payPalHostedFieldsContext.ts
- src/context/scriptProviderContext.ts
- src/hooks/payPalHostedFieldsHooks.ts
- src/stories/PayPalMessages.stories.tsx
- src/stories/braintree/BraintreePayPalButtons.stories.tsx
- src/stories/constants.ts
- src/stories/payPalButtons/PayPalButtons.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFieldsProvider.stories.tsx
- src/stories/payPalMarks/PayPalMarks.stories.tsx
- src/stories/payPalScriptProvider/PayPalScriptProvider.stories.tsx
- src/stories/subscriptions/Subscriptions.stories.tsx
- src/stories/venmo/VenmoButton.stories.tsx
- src/types/braintreePayPalButtonTypes.ts
- src/types/paypalButtonTypes.ts
- src/types/scriptProviderTypes.ts
The PR changes the way to import types from `paypal-js`, now we can import directly from the library without need to specify the paths.
To make it cleaner the way final users import types from the `paypal-js` dependency. Now we have access to all exported types from the default `index.d.ts` in the `paypal-js` library.
Previous imports:
Current imports:
> Replace absolute imports types from paypal-js

- src/components/PayPalButtons.tsx
- src/components/PayPalMarks.tsx
- src/components/PayPalMessages.tsx
- src/components/PayPalScriptProvider.test.tsx
- src/components/PayPalScriptProvider.tsx
- src/components/braintree/BraintreePayPalButtons.test.tsx
- src/components/braintree/BraintreePayPalButtons.tsx
- src/components/hostedFields/PayPalHostedFieldsProvider.test.js
- src/components/hostedFields/PayPalHostedFieldsProvider.tsx
- src/components/hostedFields/utils.test.js
- src/components/hostedFields/utils.ts
- src/constants.ts
- src/context/scriptProviderContext.ts
- src/hooks/contextValidator.test.ts
- src/hooks/contextValidator.ts
- src/hooks/scriptProviderHooks.ts
- src/utils.test.ts
This PR supports the data-user-id-token option key on the provider, allowing the final user to set their Braintree tokenization keys. In the previous version, the BraintreePayPalButtons component only supports data-client-token, forcing the final user to make integrations using only the JWT client tokens.
This change allows making the Braintree integration using either the client token or the client tokenization key. Also solve this reported bug: https://github.com/paypal/react-paypal-js/issues/214. To find more info refer to this Jira ticket: https://engineering.paypalcorp.com/jira/browse/DTPPSDK-541
Users can integrate the Braintree as follow:
```js
<PayPalScriptProvider
options={{
"client-id": "your-client-id"
"data-client-token": "your-client-token",
// "data-user-id-token": …
```
> Support Braintree tokenization keys

- src/types/braintree/paypalCheckout.ts
the property `requestBillingAgreement` is expected in order to use the **Checkout with Vault** flow:
https://developer.paypal.com/braintree/docs/guides/paypal/checkout-with-vault
> fix: missing type billing agreement option on createPayment

- src/components/PayPalScriptProvider.test.tsx
- src/components/braintree/BraintreePayPalButtons.tsx
- src/stories/braintree/code.ts
This PR contains the needed update in order to make clear how the clients can use the Braintree integration using the client token or the tokenization key.
To avoid confusion on how to integrate Braintree using the PayPal react library. Now some users are using the same key `data-client-token` to integrate using both the client-token and the tokenization-key, resulting in an error in the component because the `data-client-token` is not a JWT token and can't be decoded.
Set in the `PayPalSriptProvider` options a Braintree tokenization key under the `data-client-token`. The library started failing because can't decode the tokenization key string. 
Previous version:
Update:
> Braintree integration story update

- src/stories/PayPalMessages.stories.tsx
- src/stories/braintree/BraintreePayPalButtons.stories.tsx
- src/stories/payPalButtons/PayPalButtons.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFieldsProvider.stories.tsx
- src/stories/payPalMarks/PayPalMarks.stories.tsx
- src/stories/payPalScriptProvider/PayPalScriptProvider.stories.tsx
- src/stories/subscriptions/Subscriptions.stories.tsx
- src/stories/venmo/VenmoButton.stories.tsx
The PR updates the way to get access to the `context.args` set on the controls by default or after users' interaction.
These changes are required because the `context.args` key will be deleted on version 7 of the storybook.
Meaning our stories will break in the future after we update the storybook from version 6 to version 7.
Changes are only in the story's scope not introduce any change in the behavior of the library.
> Update the way to get args from the story context

- src/components/braintree/BraintreePayPalButtons.tsx
- src/components/braintree/utils.test.ts
- src/components/braintree/utils.ts
- src/types/braintreePayPalButtonTypes.ts
The PR enables a new property on the `BraintreePayPalButtons` component allowing to pass a `braintreeNamespace`. If this new property is set in the component the default behavior of loading the Braintree scripts from the CDN will be skipped and the component will trust on the `braintreeNamespace`  manually set by the consumer of the component.
This change is related to this [issue](https://github.com/paypal/react-paypal-js/issues/215). If a consumer of the library is using AMD/UMD modules the Braintree scripts don't create the `window.braintree` namespace in the global context, meaning the `BraintreePayPalButtons` will fail on the render process because is not capable to get access to the global Braintree namespace. Check more in …
> Enable braintreeNamespace property on the BraintreePayPalButtons component

- package-lock.json
- package.json
- src/components/PayPalMarks.test.tsx
- src/components/__snapshots__/PayPalMarks.test.tsx.snap
- src/components/hostedFields/PayPalHostedField.test.tsx
- src/components/hostedFields/PayPalHostedFieldsProvider.test.tsx
- src/components/hostedFields/utils.test.ts
- src/context/scriptProviderContext.test.ts
- src/hooks/payPalHostedFieldsHooks.test.ts
The PR contains the needed changes to migrate from `js` test files to `ts` or `tsx` files. Also contains some enhancement in the test coverage per file.
To standardize the test files extension and use typescript files over native javascript files.
Related ticket [JIRA](https://engineering.paypalcorp.com/jira/browse/DTPPSDK-647).
The PR depends on this [PR](https://github.com/paypal/react-paypal-js/pull/240), because some breaking changes were introduced, meaning the unit test changed as well.
> Migrate test files from JS to TS/TSX files

- package-lock.json
- package.json
- scripts/check-node-version.js
Remove the `node-check-version` dependency and replace it with using `process.version` and the `semver` library directly.
Same as https://github.com/paypal/paypal-js/pull/155
> chore: use semver for validating node version

- src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx
The PR fix a problem with the hosted fields stories. The `createOrder` function is failing since is sending an `undefined` value in `currency_code`.
To fix the broken hosted fields stories.
> chore: HostedFields stories are failing

- src/components/braintree/BraintreePayPalButtons.test.tsx
- src/components/braintree/BraintreePayPalButtons.tsx
- src/components/braintree/utils.test.ts
- src/components/braintree/utils.ts
- src/constants.ts
- src/types/braintree/paypalCheckout.ts
The PR contains an enhancement on the Braintree integration. A new missing case was added to the React Braintree integration allowing the use of the `merchant-id` in the `paypalCheckout.create` function initialization.
In the current version, the solution only supports the client instance, but the final clients aren't able to use the `merchantAccountId` option on the checkout initialization process.
More details [here](https://engineering.paypalcorp.com/jira/browse/DTPPSDK-754)
> Support merchant-id on checkout creation

- src/stories/payPalHostedFields/codeHostedFields.ts
The HostedFields example is broken due to the code template being wrong and it isn't calling the `getState` function from the `cardFields`.
###
Why are we making these changes?
To fix the failing HostedFields example in Codesanbox.
> fix(hostedFields): problems with code template

- package-lock.json
- package.json
- src/components/hostedFields/PayPalHostedFieldsProvider.test.tsx
- src/components/hostedFields/PayPalHostedFieldsProvider.tsx
- src/stories/payPalHostedFields/codeHostedFields.ts
- src/types/payPalHostedFieldTypes.ts
The PR contains code improvements for the `PayPalHostedFieldsProvider` component in order to enable the `installments` option in the render process of the hosted fields.
A short description can be found [here](https://engineering.paypalcorp.com/jira/browse/DTPPSDK-765)
The main reason to make the change is to allow clients to use the `installments` option in the hosted fields render process. The previous version does not expose the ability to set the `installments` callback.
https://github.com/paypal/paypal-js/pull/239
> feat(hostedFields): enable installments option

- src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx
- src/stories/payPalHostedFields/codeHostedFields.ts
The PR includes a code change about how to use the Hosted Fields. Instead of using an alias changing the `cardFields` name to `hostedField`, the idea is to go straight with the instance and the key as follows: `hostedField.cardFields`.
The example code for Hosted Fields can introduce some confusion because we're using an alias on line 75 of the file `PayPalHostedFields.stories.tsx` take a look [here](https://github.com/paypal/react-paypal-js/blob/904c580046c1f7d3d83311ab735f1a56c856f8ff/src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx#L75)
More details [here](https://engineering.paypalcorp.com/jira/browse/DTPPSDK-778)
Before:
After:
> chore(story): update the Hosted Fields story example

- src/components/PayPalButtons.test.tsx
- src/components/PayPalButtons.tsx
- src/components/PayPalMarks.test.tsx
- src/components/PayPalMarks.tsx
- src/components/PayPalMessages.test.tsx
- src/components/PayPalMessages.tsx
- src/components/PayPalScriptProvider.tsx
- src/components/braintree/BraintreePayPalButtons.tsx
- src/components/hostedFields/PayPalHostedField.test.tsx
- src/components/hostedFields/PayPalHostedField.tsx
- src/components/hostedFields/PayPalHostedFieldsProvider.test.tsx
- src/components/hostedFields/PayPalHostedFieldsProvider.tsx
- src/components/hostedFields/hooks.ts
- src/context/scriptProviderContext.ts
- src/hooks/scriptProviderHooks.ts
- src/stories/PayPalMessages.stories.tsx
- src/stories/braintree/BraintreePayPalButtons.stories.tsx
- src/stories/commons.tsx
- src/stories/components/CopyButton.tsx
- src/stories/components/CustomSandpack.tsx
- src/stories/payPalButtons/PayPalButtons.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFieldsProvider.stories.tsx
- src/stories/payPalMarks/PayPalMarks.stories.tsx
- src/stories/payPalScriptProvider/PayPalScriptProvider.stories.tsx
- src/stories/subscriptions/Subscriptions.stories.tsx
- src/stories/venmo/VenmoButton.stories.tsx
Remove the `import { type TYPE }` to avoid problems with an older version of Typescript.
Check details [here](https://engineering.paypalcorp.com/jira/browse/DTPPSDK-782)
> chore(typescript): remove type from import

- src/components/PayPalScriptProvider.test.tsx
- src/components/PayPalScriptProvider.tsx
- src/context/scriptProviderContext.ts
- src/types/enums.ts
- src/types/scriptProviderTypes.ts
Probably naive first attempt to expose error message in case of rejected script load
> feat: add loadingStatusErrorMessage to state

- src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx
- src/stories/payPalHostedFields/PayPalHostedFieldsProvider.stories.tsx
- src/stories/payPalHostedFields/codeHostedFields.ts
- src/stories/payPalHostedFields/codeProvider.ts
The current sandbox Client ID for the Hosted Card Fields Storybook demo is ineligible. This PR changes it to use a new Client ID that is eligible.
> chore(storybook): change client-id for hosted-fields example

- README.md
- src/stories/payPalButtons/PayPalButtons.stories.tsx
- src/stories/payPalButtons/code.ts
- src/stories/payPalHostedFields/PayPalHostedFields.stories.tsx
- src/stories/payPalMarks/PayPalMarks.stories.tsx
- src/stories/payPalMarks/code.ts
- src/stories/utils.ts
This PR updated the README docs and the storybook examples to use the `<PayPalButtons>` component with server-side api calls. 
```jsx
<PayPalButtons
createOrder={(data, actions) => {
// paypal helper that calls the Orders API on your behalf
return actions.order.create({ /* your order payload */ })
}}
/>
```
```jsx
<PayPalButtons
createOrder={(data, actions) => {
// fetch call to your own server that will accept whatever payload you design
// and will call the Orders API for server-to-server communcation
return fetch("/my-server/create-paypal-order", { /* your custom payload for your server */ })
}}
/>
```
> chore: recommend using server-side api calls

- src/stories/braintree/BraintreePayPalButtons.stories.tsx
- src/stories/payPalButtons/PayPalButtons.stories.tsx
This pull request updates the PayPal and Braintree buttons stories to include two new callbacks that were introduced in:
1. https://github.com/paypal/paypal-smart-payment-buttons/pull/679 and
2. https://github.com/paypal/paypal-js/pull/427
**PayPal Stories**:
**Braintree Buttons**:
I was hoping to mark the `onShippingChange` callback deprecated within Storybook, but [this issue](https://github.com/storybookjs/storybook/issues/9721#issuecomment-1668176147) suggests it is only possible if we update the JSDoc comment to explicitly have the word `deprecated` (instead of or in addition to the `@deprecated` tag)
> Update stories to include new shipping callbacks

- package-lock.json
- package.json
- src/types/payPalHostedFieldTypes.ts
- src/utils.test.ts
- src/utils.ts
This PR updates the `components` type to match the updated type in paypal-js, from: https://github.com/paypal/paypal-js/pull/420/files#diff-2be14baaff5c425c93291f46a925c3a5bc3e78c438c9d39620bdbc0c154a17f7R5
> Fix failing typecheck

- .github/workflows/publish.yml
- .github/workflows/storybook.yml
- .github/workflows/validate.yml
Upgrading to `actions/checkout` v3 in attempts to fix the npm publish Github Action.
> chore(ci): upgrade to the checkout action v3

- .github/workflows/publish.yml
Attempting to fix the following error from https://github.com/paypal/react-paypal-js/actions/runs/8087741241/job/22100366726:
```
✔ tagging release v8.1.4
ℹ Run `git push --follow-tags origin main && npm publish` to publish
> @paypal/react-paypal-js@8.1.3 postrelease
> git push && git push --follow-tags && npm run build && npm publish
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Required status check "main" is expected.        
To https://github.com/paypal/react-paypal-js
! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/paypal/react-paypal-js'
Error: Process completed with exit code 1.
```
> chore(ci): fix github permission with publish step

- src/components/PayPalScriptProvider.test.tsx
- src/types/scriptProviderTypes.ts
PR to simplify the type for the ScriptReducerAction (PayPalScriptProvider component).
This refactoring allows the use of this npm package in projects with lower TS versions, which doesn't support template literals in type definitions. Methods such as excluding in tsconfig, skipLibCheck, ts ignore, and no-check were unsuccessful.
The type definition has been simplified, and the test case updated.
> refactor: simplify template literals in types definition for ScriptReducerAction 
